version: 2

jobs:
  build:
    docker:
      - image: debian:stretch
    steps:
      - checkout
      - run:
          name: Greeting
          command: echo Hello, world.
      - run:
          name: Print the Current Time
          command: date
  build:
    steps:
      - run:
          name: current directory
          command: pwd
      - run:
          name: test build
          shell: /bin/sh 
          command: make test
