version: 2
jobs:
  build:
    docker:
      - image: ubuntu:xenial
    steps:
      - checkout
      - run: ls -la
      - run: apt-get update
      - run: apt-get -y install build-essential
      - run: apt-get -y install curl
      - run: apt-get -y install unzip
      - run: apt-get -y install git-all
      - run: apt-get -y install awscli
      - run: mkdir ~/.aws
      - run: curl -fSL "https://releases.hashicorp.com/terraform/0.11.3/terraform_0.11.3_linux_amd64.zip" -o terraform.zip
      - run: unzip terraform.zip -d /opt/terraform
      - run: ln -s /opt/terraform/terraform /usr/bin/terraform
      - run: rm -f terraform.zip
      - run: mkdir ~/.ssh
      - run: ssh-keygen -t rsa -N '' -f ~/.ssh/dev_key -C "dev_key"
      - run:
          command: |
            echo Running test - terraform init
            cd terraform
            terraform init -backend-config="bucket=aws-terraform-state-bucket" -backend-config="key=vpc-with-bastionbox.tfstate" -backend-config="region=us-west-1" -var-file=./environments/dev/inputs.tfvars
      - run:
          command: |
            echo Running test - terraform validate
            cd terraform
            terraform validate -var-file=./environments/dev/inputs.tfvars
